# Generated by Django 4.1 on 2022-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
