# Generated by Django 4.1 on 2022-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0009_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
