# Generated by Django 4.1 on 2022-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0010_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
